version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=235691gg
    depends_on:
      - postgres

  redis:
    image: "redis:alpine"

  celery:
    build: .
    command: celery -A deployDjango worker --loglevel=INFO
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres

  postgres:
    image: postgres:13  # Use the version you prefer
    restart: always
    environment:
      POSTGRES_DB: postgres  # The name of the database to create
      POSTGRES_USER: postgres   # Default user
      POSTGRES_PASSWORD: 235691gg # Set a strong password
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data

volumes:
  postgres_data:  # Named volume for persisting postgres data