# Generated by Django 5.1.1 on 2024-10-18 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_instructor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='order_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_buy',
        ),
    ]
